### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/ex_multihash#3]
Hey @zabirauf!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by zabirauf** [comment]
Hey @RichardLitt!

I'll be glad to move the repository to the Multiformats organization. Let me know when do you want me to initiate the transfer as I think you have to add me to the organization and give me the admin rights so that i can transfer the repo.

**Comment by RichardLitt** [comment]
Hey @zabirauf! Awesome. Added you to the organization; AFAIK, you should be able to transfer it now. I'm trying to limit admin rights to the entire organization, for security reasons, but I or @jbenet would happily transfer it over if you can't yourself. If you transfer it to me, or him (as you and I haven't interacted before), we can transfer it over to multiformats. I'll add you as an admin of the repo as soon as that is done. Sound good?

**Comment by zabirauf** [comment]
@RichardLitt I was able to transfer the repo to Multiformats organization.

**Comment by RichardLitt** [comment]
Awesome Done. :) Thank you!

Let me know if I can help out any other way: I'll probably PR with a README update in a day or two.
